# Generated by Django 3.0.5 on 2020-04-19 03:30

import Profile.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('customer_id', models.CharField(blank=True, max_length=120, null=True)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('GraduationDate', models.DateField(blank=True, null=True)),
                ('aboutme', models.TextField(blank=True, max_length=300)),
                ('experience', models.TextField(blank=True, max_length=300)),
                ('preferences', models.TextField(blank=True, max_length=300)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Student'), (2, 'Teacher'), (3, 'Supervisor')], null=True)),
                ('major', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Computer Engineering'), (2, 'Computer Science'), (3, 'Software Engineering'), (4, 'Electrical Engineering')], null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=Profile.models.upload_image_path)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_digital', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.Profile')),
            ],
        ),
    ]
