# Generated by Django 3.0.4 on 2020-04-13 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20200412_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationdata',
            name='password1',
        ),
    ]
